Gemfile:
  required:
    ':development':
      - gem: 'toml-rb'
      - gem: rspec-puppet-facts
        version: '>= 2.0.1'

spec/default_facts.yml:
  extra_facts:
    pe_server_version: 2019.8.4
    pe_build: 2019.8.4
    
spec/spec_helper.rb:
  mock_with: ":rspec"