# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
 
      - name: action-pdk-validate
  # You may pin to the exact commit or the version.
  # uses: puppets-epic-show-theatre/action-pdk-validate@31b5407676af16b690b2b8c54c0767af72fcc34f
        uses: puppets-epic-show-theatre/action-pdk-validate@v1.0.0
        with:
    # A string indicating the Puppet version to validate against, such as "5.4.2" or "5.5".
          puppet-version: # optional
    # A string indicating the PE version to validate against, such as "2017.3.5" or "2018.1".
          pe-version: # optional

      - name: ShellCheck
  # You may pin to the exact commit or the version.
  # uses: ludeeus/action-shellcheck@d586102c117f97e63d7e3b56629d269efc9a7c60
        uses: ludeeus/action-shellcheck@1.0.0
        with:
    # A space seperated list of additional filename to check
          additional_files: # optional, default is 
    # Paths to ignore when running ShellCheck
          ignore: # optional, default is 
    # Minimum severity of errors to consider. Options: [error, warning, info, style]
          severity: # optional, default is 
    # Run shellcheck on _all_ files at once, instead of one at a time
          check_together: # optional, default is 
    # Directory to be searched for files. Defaults to .
          scandir: # optional, default is .
    # Set to true to skip using problem-matcher
          disable_matcher: # optional, default is false
